### ISSUE TITLE
infografia ciclo de vida de desarrollo de sofware 

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-1-infografia-Rufino07#2]
[infografia -ciclo de vida desarrollador de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Rufino07/files/12481968/infografia.-ciclo.de.vida.desarrollador.de.software.pdf)

**Comment by ToniDepp** [comment]
Redacción y ortografía: Detalles mínimos 3 puntos de 3 puntos
Exposición de ideas centrales: Buen manejo de los recursos 3 puntos de 3 puntos
Organización de la información: un poco rebuscado el orden 2.5 puntos de 3 puntos
Uso de imágenes y colores: Hacen buen complemento 3 puntos de 3 puntos
Presentación visual: Buen diseño 3 puntos de 3 puntos
Referencias: No se menciona ni uno 0 puntos de 2 puntos 
Presentación: 3 puntos de 3 puntos
Calificación: 17.5/ 20
Calificado por: Eduardo Tomas

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
